title: Khosifa Sintari # your name (or website title) here
logo: "/images/Khosifa.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Semester 7 Akuntansi FEB UM | Data Analytics Studi Independen bersama Zenius
  <br><br>
  <a href="https://www.linkedin.com/in/khosifa-sintari/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
